# Generated by Django 3.2.5 on 2021-08-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
