# Generated by Django 3.2.5 on 2021-11-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20211104_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='room_number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
