# Generated by Django 3.2.5 on 2021-11-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
